public class NKS_Henvendelse {
    public String aktorId;
    public String applikasjonsId;
    public String avsluttetDato;
    public String behandlingsId;
    public String behandlingskjedeId;
    public String behandlingstema;
    public String brukersEnhet;
    public String eksternAktor;
    public Boolean erTilknyttetAnsatt;
    public Boolean ferdigstiltUtenSvar;
    public String fnr;
    public String gjeldendeTemagruppe;
    public String henvendelseIdGsak;
    public String henvendelseType;
    public NKS_JournalfortInformasjon journalfortInformasjon;
    public String kontorsperreEnhet;
    public String korrelasjonsId;
    public String lestDato;
    public NKS_Markeringer markeringer;
    public NKS_HenvendelseMetadataListe metadataListe;
    public String markertSomFeilsendtAv;
    public String oppgaveIdGsak;
    public String opprettetDato;
    public String tema;
    public String tilknyttetEnhet;
}
