name: "[HELPER] Install package with dependent packages"
on:
  workflow_dispatch:
    inputs:
      packageId:
        description: "Package ID"
        required: true
      org:
        description: "Org (preprod, dev, uat, sit)"
        required: true
jobs:
  debug:
    name: Debug Information
    runs-on: ubuntu-latest
    steps:
      - name: Print input values
        run: |
          echo "Org: ${{ github.event.inputs.org }}"
          echo "Package ID: ${{ github.event.inputs.packageId }}"
          echo "Initiator: ${{ github.actor }}"

  deploy-package:
    name: Deploy Package
    runs-on: ubuntu-latest
    steps:
      # Set SFDX Auth URL
      - name: Set SFDX Auth URL
        id: auth-url
        run: |
          if [ ${{ github.event.inputs.org }} == "preprod" ];then
            echo "::set-output name=target::$(echo ${{ secrets.CRM_PREPROD_SFDX_URL }})"
            echo "'preprod' was set"
          elif [ ${{ github.event.inputs.org }} == "dev" ];then
            echo "::set-output name=target::$(echo ${{ secrets.DEV_SFDX_URL }})"
            echo "'dev' was set"
          elif [ ${{ github.event.inputs.org }} == "uat" ];then
            echo "::set-output name=target::$(echo ${{ secrets.CRM_UAT_SFDX_URL }})"
            echo "'preprod' was set"
          elif [ ${{ github.event.inputs.org }} == "sit" ];then
            echo "::set-output name=target::$(echo ${{ secrets.CRM_SIT_SFDX_URL }})"
            echo "'sit' was set"
          fi

      # Install and Authorize SFDX
      - name: Authorize SFDX
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ steps.auth-url.outputs.target }}

      # Install sfpowerkit plugin used to install multiple packages only by version number
      - name: Install sfpowerkit plugin
        run: echo y | sfdx plugins:install sfpowerkit

      # Checkout source code
      - name: Checkout source code from master
        uses: actions/checkout@v2

      # Get package keys
      - name: Get package keys
        id: install-keys
        run: |
          keys=""
          for p in $(jq '.result | .[].Name' -r <<< "$(sfdx force:package:list --json)"); do
              keys+=$p":${{ secrets.CRM_PACKAGE_KEY }} "
          done

          echo "::set-output name=keys::$(echo $keys)"
      
      # Install packages this repo is dependant on
      - name: Install dependant packages
        run: sfdx sfpowerkit:package:dependencies:install -r -a -w 60 -k '${{ steps.install-keys.outputs.keys }}'

      # Install package in target org
      - name: Install package in target org
        run: sfdx force:package:install --package ${{ github.event.inputs.packageId }} -k ${{ secrets.CRM_PACKAGE_KEY }} -w 10 -b 10 -r

      # Deploy unpackagable content
      - name: Deploy unpackagable content
        run: |
          if [ -d "./force-app/unpackagable-with-auto-deploy" ]; then
            echo "Starting deployment of ./force-app/unpackagable-with-auto-deploy"
            sfdx force:source:deploy -p ./force-app/unpackagable-with-auto-deploy -l RunLocalTests
          fi
