# Unique name for this workflow
name: "[Pull Request] Validate Metadata"

# Definition when the workflow should run
on:
  pull_request:
    branches:
      - "*"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install

      # Checkout the code in the pull request
      - name: "Checkout source code"
        uses: actions/checkout@v2

      # Store secret for dev hub
      - name: "Populate auth file with PROD_SFDX_URL secret"
        shell: bash
        run: "echo ${{ secrets.PROD_SFDX_URL}} > ./PROD_SFDX_URL.txt"

      # Authenticate dev hub
      - name: "Authenticate Dev Hub"
        run: "sfdx force:auth:sfdxurl:store -f ./PROD_SFDX_URL.txt -a devhub -d"

      # Remove auth files
      - name: "Remove auth files"
        if: always()
        run: "rm -f ./PROD_SFDX_URL.txt"

      # Delete unpackagable
      - name: "Delete unpackagable"
        run: rm -rf unpackagable

      # Create scratch org
      - name: "Create scratch org"
        run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1

      # Install sfpowerkit plugin used to install multiple packages only by version number
      - name: "Install sfpowerkit plugin"
        run: "echo y | sfdx plugins:install sfpowerkit"

      # Get package keys
      - name: "Get package keys"
        id: install-keys
        run: |
          keys=""
          for p in $(jq '.result | .[].Name' -r <<< "$(sfdx force:package:list --json)"); do
              keys+=$p":${{ secrets.PACKAGE_KEY}} "
          done

          echo "::set-output name=keys::$(echo $keys)"

      # Install packages this repo is dependant on
      - name: "Install dependant packages"
        run: "sfdx sfpowerkit:package:dependencies:install -u scratch-org -r -a -w 60 -k '${{ steps.install-keys.outputs.keys }}'"

      # Deploy source to scratch org
      - name: "Push source to scratch org"
        run: "sfdx force:source:push"

      # Sleep for 1 minute while permset groups are updating
      - name: Sleep for 1 minute while permset groups are updating
        uses: jakejarvis/wait-action@master
        with:
          time: "1m"

      # Run Apex tests in scratch org
      - name: "Run Apex tests"
        # run: "sfdx force:apex:test:run -l RunLocalTests -c -r human -d ./tests/apex -w 30"
        run: sfdx force:source:deploy -m ApexClass --testlevel=RunLocalTests --checkonly

      # Create users
      - name: "Create users"
        if: contains( github.event.pull_request.labels.*.name, 'saveScratchOrg')
        id: create-users
        run: |
          sfdx force:user:create -f config/users/pull_request.json -u scratch-org -a employee
          echo "::set-output name=loginUrl::$(sfdx force:user:password:generate --onbehalfof=scratch-org)"

          admin=$(sfdx force:user:display -u scratch-org --json)
          employee=$(sfdx force:user:display -u employee --json)

          echo "::set-output name=instanceUrl::$( echo $admin | jq -r '.result.instanceUrl' )"

          echo "::set-output name=adminUsername::$( echo $admin | jq -r '.result.username' )"
          echo "::set-output name=adminPassword::$( echo $admin | jq -r '.result.password' )"
          echo "::set-output name=adminInstantLogin::$( sfdx force:org:open -u scratch-org -r --json | jq -r '.result.url' )"

          echo "::set-output name=employeeUsername::$( echo $employee | jq -r '.result.username' )"
          echo "::set-output name=employeePassword::$( echo $employee | jq -r '.result.password' )"
          echo "::set-output name=employeeInstantLogin::$( sfdx force:org:open -u employee -r --json | jq -r '.result.url' )"

      # Slack Notification
      - name: "Slack Notification"
        if: contains( github.event.pull_request.labels.*.name, 'saveScratchOrg')
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: "Scratch Organization Aficionado"
          SLACK_MESSAGE: |
            *Login to Scratch Org*

            URL: ${{steps.create-users.outputs.instanceUrl}}

            *Admin User:*
            Username: ${{ steps.create-users.outputs.adminUsername }}
            Password: ${{ steps.create-users.outputs.adminPassword }} (valid for 24 hours)
            Instant login: ${{ steps.create-users.outputs.adminInstantLogin }} (valid for 2 hours)

            *NAV Employee User:*
            Username: ${{ steps.create-users.outputs.employeeUsername }}
            Password: ${{ steps.create-users.outputs.employeePassword }} (valid for 24 hours)
            Instant login: ${{ steps.create-users.outputs.employeeInstantLogin }} (valid for 2 hours)

      # Delete scratch orgs
      - name: "Delete scratch org"
        if: failure() || !contains( github.event.pull_request.labels.*.name, 'saveScratchOrg')
        run: "sfdx force:org:delete -p -u scratch-org"
