global class NKS_GroupVariables {
    public static final String VEILEDER_GROUP_NAME = 'group_41002';
    public static final String SKJERMET_GROUP_NAME = 'group_410099';
    public static final String FORTROLIG_GROUP_NAME = 'group_999908';
    public static final String FORTROLIG_SKJERMET_GROUP_NAME = 'group_999905';
    public static final String TEMA_BID_NAME = 'Tema_BID';
    public static final String FORTROLIG_BID_NAME = 'Fortrolig_BID';
    public static final String SKJERMET_BID_NAME = 'Skjermet_BID';
    public static final String FORTROLIG_SKJERMET_BID_NAME = 'Fortrolig_Skjermet_BID';
    public static final String TEMA_SER_NAME = 'Tema_SER';
    public static final String FORTROLIG_SER_NAME = 'Fortrolig_SER';
    public static final String SKJERMET_SER_NAME = 'Skjermet_SER';
    public static final String FORTROLIG_SKJERMET_SER_NAME = 'Fortrolig_Skjermet_SER';
}
